name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: gogogo
        run: |
          echo "${{ secrets.SECRET_KEY }}" > ~/matchingkey.pem
          chmod 600 ~/matchingkey.pem
          ssh -t -t root@"${{ secrets.PROD_HOST }}" -i ~/matchingkey.pem
          ls -al
    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.9'
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py runserver 8068
