name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Copy code to remote
        run: |
          echo "${{ secrets.SECRET_KEY }}" > ~/matchingkey.pem
          chmod 600 ~/matchingkey.pem
          ssh -o StrictHostKeyChecking=no -i ~/matchingkey.pem root@${{ secrets.PROD_HOST }} "rm -rf ~/blind_date; mkdir -p ~/blind_date"
          # Copy files from the current branch to remote host using scp
          scp -o StrictHostKeyChecking=no -i ~/matchingkey.pem -r $GITHUB_WORKSPACE/* root@${{ secrets.PROD_HOST }}:~/blind_date
          ssh -o StrictHostKeyChecking=no -i ~/matchingkey.pem root@${{ secrets.PROD_HOST }} "sh ~/blind_date/release.sh"
          EXIT_CODE=$?

          # Check the exit code and set the job outcome
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Remote script execution successful"
          else
            echo "Remote script execution failed with exit code $EXIT_CODE"
            exit 1
          fi
    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.9'
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py runserver 8068
